In [33]:
import pandas as pd

# Преобразование даты и работа с элементами даты

In [34]:
df = pd.DataFrame (
    {
        "name": ["Объект1", "Объект2", "Объект3"],
        "myStrDate": ["2022-09-01",   "2022-09-02",     "2022-09-03"], 
    }
 )

df

      name   myStrDate
0  Объект1  2022-09-01
1  Объект2  2022-09-02
2  Объект3  2022-09-03

In [35]:
df["myStrDate"] # получить столбец. Тип данных результата - object (строковый/смешанный)

0    2022-09-01
1    2022-09-02
2    2022-09-03
Name: myStrDate, dtype: object

In [36]:
#https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
pd.to_datetime(df["myStrDate"],  format='%Y-%m-%d')  # Передать зачения столбеца в функцию преобразования к типу Дата/время. Тип данных - datetime64[ns]

0   2022-09-01
1   2022-09-02
2   2022-09-03
Name: myStrDate, dtype: datetime64[ns]

In [37]:
df["parsedDate"] = pd.to_datetime(df["myStrDate"],  format='%Y-%m-%d', ) # результат добавить в исх. таблицу новым столбцом

In [38]:
df

      name   myStrDate parsedDate
0  Объект1  2022-09-01 2022-09-01
1  Объект2  2022-09-02 2022-09-02
2  Объект3  2022-09-03 2022-09-03

In [39]:
df["parsedDate"].dt.dayofweek # номер дня недели
df["parsedDate"].dt.day   # номер дня в месяце
df["parsedDate"].dt.month # номер месяца в году
df["parsedDate"].dt.week # номер недели в году
df["parsedDate"].dt.year # год

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  after removing the cwd from sys.path.

0    2022
1    2022
2    2022
Name: parsedDate, dtype: int64

# Замена значений (mapping)

In [40]:
df = pd.DataFrame (
    {
        "name": ["Объект1", "Объект2", "Объект3", "Объект4"],
        "NameDayOfWeek": ["Понедельник",   "Вторник",   "Среда",  "Понедельник"], 
    }
 )

df

      name NameDayOfWeek
0  Объект1   Понедельник
1  Объект2       Вторник
2  Объект3         Среда
3  Объект4   Понедельник

In [41]:
df["NameDayOfWeek"] # получить столбец. Тип данных результата - object (строковый/смешанный)

0    Понедельник
1        Вторник
2          Среда
3    Понедельник
Name: NameDayOfWeek, dtype: object

In [42]:
df["NameDayOfWeek"].nunique() # получить количество уникальных значений в столбце

3

In [43]:
df["NameDayOfWeek"].unique() # получить множество уникальных значений в столбце

array(['Понедельник', 'Вторник', 'Среда'], dtype=object)

In [44]:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html
# применить карту соотвествий имеющихся и новых значений. Тип данных результата - object (строковый/смешанный)
df['NameDayOfWeek'].map(
  {
    "Понедельник": 'Monday', 
    "Вторник": 'Tuesday', 
    "Среда": 'Wednesday', 
  } 
)

0       Monday
1      Tuesday
2    Wednesday
3       Monday
Name: NameDayOfWeek, dtype: object

In [45]:
# применить карту соотвествий имеющихся и новых значений. Тип данных результата - int64 (целочисленный)
df['NameDayOfWeek'].map(
  {
    "Понедельник": 1, 
    "Вторник": 2, 
    "Среда": 3, 
  } 
)

0    1
1    2
2    3
3    1
Name: NameDayOfWeek, dtype: int64

In [46]:
# результат добавить в исх. таблицу новым столбцом
df["NumberDayOfWeek"] = df['NameDayOfWeek'].map(
  {
    "Понедельник": 1, 
    "Вторник": 2, 
    "Среда": 3, 
  } 
)
df

      name NameDayOfWeek  NumberDayOfWeek
0  Объект1   Понедельник                1
1  Объект2       Вторник                2
2  Объект3         Среда                3
3  Объект4   Понедельник                1

# Фильтация значений

In [53]:
N = 8
df = pd.DataFrame({
  'Integer_col': range(100, 100+N),
  'Str_col': [chr(97 + i) for i in range(N)],
  'isYes_col': ['yes', 'no']* (N//2),
 })
df

   Integer_col Str_col isYes_col
0          100       a       yes
1          101       b        no
2          102       c       yes
3          103       d        no
4          104       e       yes
5          105       f        no
6          106       g       yes
7          107       h        no

In [54]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
df.query('Integer_col>102  &  isYes_col=="yes"')

   Integer_col Str_col isYes_col
4          104       e       yes
6          106       g       yes